name: Qodana
on:
  workflow_dispatch:
  pull_request:
  push:
jobs:
  qodana-backend:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      checks: write
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}  # to check out the actual pull request commit, not the merge commit
          fetch-depth: 0  # a full history is required for pull request analysis
      - name: 'Use qodana-backend config'
        run: cp .github/qodana-backend.yaml qodana.yaml
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.SPACE_REGISTRY }}
          username: ${{ secrets.SPACE_LOGIN }}
          password: ${{ secrets.SPACE_TOKEN }}

      - name: 'Qodana Backend'
        uses: JetBrains/qodana-action@v2023.2
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
        with:
          args: |
            --source-directory,backend,
            --baseline,qodana-backend.sarif.json,
            --fail-threshold,0,
            -l,${{ secrets.SPACE_REGISTRY }}/p/sa/containers/qodana-jvm:2023.3-rc
          upload-result: true
          artifact-name: qodana-backend
  qodana-frontend:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      checks: write
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}  # to check out the actual pull request commit, not the merge commit
          fetch-depth: 0  # a full history is required for pull request analysis
            
      - name: 'Use qodana-frontend config'
        run: cp .github/qodana-frontend.yaml qodana.yaml

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.SPACE_REGISTRY }}
          username: ${{ secrets.SPACE_LOGIN }}
          password: ${{ secrets.SPACE_TOKEN }}


      - name: 'Qodana Frontend'
        if: success() || failure()
        uses: JetBrains/qodana-action@v2023.2
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
        with:
          args: |
            --source-directory,frontend,
            --baseline,qodana-frontend.sarif.json,
            --fail-threshold,0,
            -l,${{ secrets.SPACE_REGISTRY }}/p/sa/containers/qodana-jvm:2023.3-rc
          upload-result: true
          artifact-name: qodana-frontend
